[package]
name = "miez-backend"
version = "0.1.0"
authors = ["mediaman <hello@mediaman.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "miez-backend"
path = "src/main.rs"
